//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.cpp.calypso.web {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesWeb() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.cpp.calypso.web.MensajesWeb", typeof(MensajesWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing application setting &apos;{0}&apos;.
        /// </summary>
        public static string ConfigurationErrors_MissingApplicationSetting_ErrorMessage {
            get {
                return ResourceManager.GetString("ConfigurationErrors_MissingApplicationSetting_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteres no permitidos.
        /// </summary>
        public static string DataTypeAttribute_CaracterEspecialValidationError {
            get {
                return ResourceManager.GetString("DataTypeAttribute_CaracterEspecialValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser una fecha..
        /// </summary>
        public static string DataTypeAttribute_DateValidationError {
            get {
                return ResourceManager.GetString("DataTypeAttribute_DateValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe un inconveniente, vuelva a intentar más tarde.
        /// </summary>
        public static string ErrorGenerico {
            get {
                return ResourceManager.GetString("ErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Usuario con la misma Identificación ó Cuenta.
        /// </summary>
        public static string GestionUsuariosUsuarioDuplicado {
            get {
                return ResourceManager.GetString("GestionUsuariosUsuarioDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario eliminado exitosamente.
        /// </summary>
        public static string GestionUsuariosUsuarioEliminadoCorrecto {
            get {
                return ResourceManager.GetString("GestionUsuariosUsuarioEliminadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario guardado exitosamente.
        /// </summary>
        public static string GestionUsuariosUsuarioGuardadoCorrecto {
            get {
                return ResourceManager.GetString("GestionUsuariosUsuarioGuardadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Campo Identificación es requerido.
        /// </summary>
        public static string IdentificacionRequerida {
            get {
                return ResourceManager.GetString("IdentificacionRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser un tipo de cadena o matriz con una longitud máxima de &apos;{1}&apos;..
        /// </summary>
        public static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para la búsqueda propuesta no existe resultados.
        /// </summary>
        public static string No_Existe_Resultado_Busqueda {
            get {
                return ResourceManager.GetString("No_Existe_Resultado_Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron resultados para la búsqueda propuesta.
        /// </summary>
        public static string NoFoundRecordsMessage {
            get {
                return ResourceManager.GetString("NoFoundRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe estar entre {1} y {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha final no debe ser inferior a la fecha inicial..
        /// </summary>
        public static string ReporteCargaHorariaViewMode_FechaFin_CompareError {
            get {
                return ResourceManager.GetString("ReporteCargaHorariaViewMode_FechaFin_CompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es obligatorio..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
    }
}
