//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.cpp.calypso.web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titulos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titulos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campusoft.Nucleo.Presentacion.Recursos.Titulos", typeof(Titulos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string AccionDiarioTematico {
            get {
                return ResourceManager.GetString("AccionDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignatura.
        /// </summary>
        public static string AsignaturaDiarioTematico {
            get {
                return ResourceManager.GetString("AsignaturaDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros de Auditoría.
        /// </summary>
        public static string Auditoria_PageTitle {
            get {
                return ResourceManager.GetString("Auditoria_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción:.
        /// </summary>
        public static string AuditoriaCriteria_Accion_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Accion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha hasta:.
        /// </summary>
        public static string AuditoriaCriteria_FechaFinal_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_FechaFinal_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha desde:.
        /// </summary>
        public static string AuditoriaCriteria_FechaInicio_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_FechaInicio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidad:.
        /// </summary>
        public static string AuditoriaCriteria_Funcionalidad_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Funcionalidad_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación:.
        /// </summary>
        public static string AuditoriaCriteria_Identificador_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Identificador_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string AuditoriaCriteria_Usuario_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Usuario_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string AuditoriaItem_Accion_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Accion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string AuditoriaItem_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidad.
        /// </summary>
        public static string AuditoriaItem_Funcionalidad_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Funcionalidad_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        public static string AuditoriaItem_Identificacion_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Identificacion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string AuditoriaItem_Registro_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Registro_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string AuditoriaItem_Usuario_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Usuario_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva.
        /// </summary>
        public static string Button_NewF {
            get {
                return ResourceManager.GetString("Button_NewF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación.
        /// </summary>
        public static string Confirmacion_Mensajes {
            get {
                return ResourceManager.GetString("Confirmacion_Mensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha actual.
        /// </summary>
        public static string General_CurrentDate {
            get {
                return ResourceManager.GetString("General_CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string General_Date {
            get {
                return ResourceManager.GetString("General_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre completo.
        /// </summary>
        public static string General_FullName {
            get {
                return ResourceManager.GetString("General_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        public static string General_Identification {
            get {
                return ResourceManager.GetString("General_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string General_Module {
            get {
                return ResourceManager.GetString("General_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han ingresado los campos obligatorios o existen datos no válidos.
        /// </summary>
        public static string General_ValidationSummary_Message {
            get {
                return ResourceManager.GetString("General_ValidationSummary_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador Curso.
        /// </summary>
        public static string IdentificadorCursoDiarioTematico {
            get {
                return ResourceManager.GetString("IdentificadorCursoDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado último proceso de Gradebook.
        /// </summary>
        public static string InformacionUltimoProcesoGradebook {
            get {
                return ResourceManager.GetString("InformacionUltimoProcesoGradebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperaciones de docentes.
        /// </summary>
        public static string LinkRecuperacionClases {
            get {
                return ResourceManager.GetString("LinkRecuperacionClases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.apellido@udla.edu.ec.
        /// </summary>
        public static string LoginMarcaAguaEjemplo {
            get {
                return ResourceManager.GetString("LoginMarcaAguaEjemplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRC.
        /// </summary>
        public static string NRC {
            get {
                return ResourceManager.GetString("NRC", resourceCulture);
            }
        }
    }
}
