// <auto-generated />
namespace com.cpp.calypso.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CertificadoIdColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CertificadoIdColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202112141532052_CertificadoIdColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
