//Encargado de Personal
export const ENCARGADO_PERSONAL_JORNALES = "J52";
export const ENCARGADO_PERSONAL_MENSUALES = "M53";
export const ENCARGADO_PERSONAL_EXPATRIADOS = "M54";
//Tipos NOmina
export const TIPO_NOMINA_JORNALES = "JOR";
export const TIPO_NOMINA_MENSUALES = "MEN";
export const TIPO_NOMINA_EXPATRIADOS = "EXP";
//Perido Nomina
export const PERIODO_NOMINA_JORNALES = "36-JORNA";
export const PERIODO_NOMINA_MENSUALES = "35-MENSU";
//Estado Civil
export const ESTADO_CIVIL_CASADO = "CAS";
export const ESTADO_CIVIL_SOLTERO = "SOL";
export const ESTADO_CIVIL_DIVORCIADO = "DIV";
export const REGISTRO_CIVIL_CASADO = "CASADO";
export const REGISTRO_CIVIL_SOLTERO = "SOLTERO";
export const REGISTRO_CIVIL_DIVORCIADO = "DIVORCIADO";
export const ESTADO_CIVIL_UNION = "UNI";
//TIPOS IDENTIFICACION
export const TIPO_IDENTIFICACION_CEDULA = "CEDULA";
export const TIPO_IDENTIFICACION_PASAPORTE = "PASAPORTE";
//GENEROS
export const GENERO_MUJER = "MUJ";
export const GENERO_VARON = "VAR";
export const REGISTRO_CIVIL_MUJER = "MUJER";
export const REGISTRO_CIVIL_HOMBRE = "HOMBRE";
//NACINALIDADES
export const NACIONALIDAD_ECUATORIANA = "239";
export const REGISTRO_CIVIL_ECUATORIANA = "ECUATORIANA";
//PARENTESCO
export const PARENTESCO_HIJO = "2-HIJO";
export const PARENTESCO_CONYUGE = "1-CÓNYUG";
export const PARENTESCO_CONVIVIENTE = "Z0-CONVI";
//VIA DE PAGO
export const VIA_PAGO_EFECTIVO = "E";
export const VIA_PAGO_CHEQUE = "C";

//Discapacidad
export const CODIGO_INCAPACIDAD_NOINCAPACITADO = "9-NOINC";
export const CODIGO_SINIESTRO_NOINCAPACITADO = "42-NOIN";

//EStados
export const ESTADO_ENVIADO_SAP = "ENVIADO SAP";

//Tipo Ausentismo
export const AUSENTISMO_PATERNIDAD = "PAT";
export const AUSENTISMO_MATERNIDAD = "MAT";

//Parametros
export const PARAMETRO_TIEMPO_PATERNIDAD = "PATERNIDAD.TIEMPO";

//Frecuencia Notificacion
export const FRECUENCIA_DIARIA = "DIA";
export const FRECUENCIA_SEMANAL = "SEM";
export const FRECUENCIA_MENSUAL = "MEN";

