//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.cpp.calypso.web {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MvcResources_Overwrite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcResources_Overwrite() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.cpp.calypso.web.Properties.MvcResources.Overwrite", typeof(MvcResources_Overwrite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current request for action &apos;{0}&apos; on controller type &apos;{1}&apos; is ambiguous between the following action methods:{2}.
        /// </summary>
        public static string ActionMethodSelector_AmbiguousMatch {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} on type {1}.
        /// </summary>
        public static string ActionMethodSelector_AmbiguousMatchType {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be greater than or equal to {0}..
        /// </summary>
        public static string ArgumentMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The asynchronous action method &apos;{0}&apos; cannot be executed synchronously..
        /// </summary>
        public static string AsyncActionDescriptor_CannotExecuteSynchronously {
            get {
                return ResourceManager.GetString("AsyncActionDescriptor_CannotExecuteSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lookup for method &apos;{0}&apos; on controller type &apos;{1}&apos; failed because of an ambiguity between the following methods:{2}.
        /// </summary>
        public static string AsyncActionMethodSelector_AmbiguousMethodMatch {
            get {
                return ResourceManager.GetString("AsyncActionMethodSelector_AmbiguousMethodMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not locate a method named &apos;{0}&apos; on controller type {1}..
        /// </summary>
        public static string AsyncActionMethodSelector_CouldNotFindMethod {
            get {
                return ResourceManager.GetString("AsyncActionMethodSelector_CouldNotFindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The provided IAsyncResult has already been consumed..
        /// </summary>
        public static string AsyncCommon_AsyncResultAlreadyConsumed {
            get {
                return ResourceManager.GetString("AsyncCommon_AsyncResultAlreadyConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The controller of type &apos;{0}&apos; must subclass AsyncController or implement the IAsyncManagerContainer interface..
        /// </summary>
        public static string AsyncCommon_ControllerMustImplementIAsyncManagerContainer {
            get {
                return ResourceManager.GetString("AsyncCommon_ControllerMustImplementIAsyncManagerContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The provided IAsyncResult is not valid for this method..
        /// </summary>
        public static string AsyncCommon_InvalidAsyncResult {
            get {
                return ResourceManager.GetString("AsyncCommon_InvalidAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The timeout value must be non-negative or Timeout.Infinite..
        /// </summary>
        public static string AsyncCommon_InvalidTimeout {
            get {
                return ResourceManager.GetString("AsyncCommon_InvalidTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not infer area name for the controller &apos;{0}&apos; because it does not have a namespace..
        /// </summary>
        public static string AttributeRouting_CouldNotInferAreaNameFromMissingNamespace {
            get {
                return ResourceManager.GetString("AttributeRouting_CouldNotInferAreaNameFromMissingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AuthorizeAttribute cannot be used within a child action caching block..
        /// </summary>
        public static string AuthorizeAttribute_CannotUseWithinChildActionCache {
            get {
                return ResourceManager.GetString("AuthorizeAttribute_CannotUseWithinChildActionCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The action &apos;{0}&apos; is accessible only by a child request..
        /// </summary>
        public static string ChildActionOnlyAttribute_MustBeInChildRequest {
            get {
                return ResourceManager.GetString("ChildActionOnlyAttribute_MustBeInChildRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} must be a date..
        /// </summary>
        public static string ClientDataTypeModelValidatorProvider_FieldMustBeDate {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} must be a number..
        /// </summary>
        public static string ClientDataTypeModelValidatorProvider_FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No route in the route table matches the supplied values..
        /// </summary>
        public static string Common_NoRouteMatched {
            get {
                return ResourceManager.GetString("Common_NoRouteMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value cannot be null or empty..
        /// </summary>
        public static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The partial view &apos;{0}&apos; was not found or no view engine supports the searched locations. The following locations were searched:{1}.
        /// </summary>
        public static string Common_PartialViewNotFound {
            get {
                return ResourceManager.GetString("Common_PartialViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property &apos;{0}&apos; cannot be null or empty..
        /// </summary>
        public static string Common_PropertyCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Common_PropertyCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property {0}.{1} could not be found..
        /// </summary>
        public static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a False.
        /// </summary>
        public static string Common_TriState_False {
            get {
                return ResourceManager.GetString("Common_TriState_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Set.
        /// </summary>
        public static string Common_TriState_NotSet {
            get {
                return ResourceManager.GetString("Common_TriState_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a True.
        /// </summary>
        public static string Common_TriState_True {
            get {
                return ResourceManager.GetString("Common_TriState_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type {0} must derive from {1}.
        /// </summary>
        public static string Common_TypeMustDriveFromType {
            get {
                return ResourceManager.GetString("Common_TypeMustDriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value &apos;{0}&apos; is invalid..
        /// </summary>
        public static string Common_ValueNotValidForProperty {
            get {
                return ResourceManager.GetString("Common_ValueNotValidForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The view &apos;{0}&apos; or its master was not found or no view engine supports the searched locations. The following locations were searched:{1}.
        /// </summary>
        public static string Common_ViewNotFound {
            get {
                return ResourceManager.GetString("Common_ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; and &apos;{1}&apos; do not match..
        /// </summary>
        public static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find a property named {0}..
        /// </summary>
        public static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A public action method &apos;{0}&apos; was not found on controller &apos;{1}&apos;..
        /// </summary>
        public static string Controller_UnknownAction {
            get {
                return ResourceManager.GetString("Controller_UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No matching action was found on controller &apos;{0}&apos;. This can happen when a controller uses RouteAttribute for routing, but no action on that controller matches the request..
        /// </summary>
        public static string Controller_UnknownAction_NoActionName {
            get {
                return ResourceManager.GetString("Controller_UnknownAction_NoActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The model of type &apos;{0}&apos; could not be updated..
        /// </summary>
        public static string Controller_UpdateModel_UpdateUnsuccessful {
            get {
                return ResourceManager.GetString("Controller_UpdateModel_UpdateUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The model of type &apos;{0}&apos; is not valid..
        /// </summary>
        public static string Controller_Validate_ValidationFailed {
            get {
                return ResourceManager.GetString("Controller_Validate_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot execute Controller with a null HttpContext..
        /// </summary>
        public static string ControllerBase_CannotExecuteWithNullHttpContext {
            get {
                return ResourceManager.GetString("ControllerBase_CannotExecuteWithNullHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A single instance of controller &apos;{0}&apos; cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request..
        /// </summary>
        public static string ControllerBase_CannotHandleMultipleRequests {
            get {
                return ResourceManager.GetString("ControllerBase_CannotHandleMultipleRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when trying to create the IControllerFactory &apos;{0}&apos;. Make sure that the controller factory has a public parameterless constructor..
        /// </summary>
        public static string ControllerBuilder_ErrorCreatingControllerFactory {
            get {
                return ResourceManager.GetString("ControllerBuilder_ErrorCreatingControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The IControllerFactory &apos;{0}&apos; did not return a controller for the name &apos;{1}&apos;..
        /// </summary>
        public static string ControllerBuilder_FactoryReturnedNull {
            get {
                return ResourceManager.GetString("ControllerBuilder_FactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The controller factory type &apos;{0}&apos; must implement the IControllerFactory interface..
        /// </summary>
        public static string ControllerBuilder_MissingIControllerFactory {
            get {
                return ResourceManager.GetString("ControllerBuilder_MissingIControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The view found at &apos;{0}&apos; was not created..
        /// </summary>
        public static string CshtmlView_ViewCouldNotBeCreated {
            get {
                return ResourceManager.GetString("CshtmlView_ViewCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The view at &apos;{0}&apos; must derive from WebViewPage, or WebViewPage&lt;TModel&gt;..
        /// </summary>
        public static string CshtmlView_WrongViewBase {
            get {
                return ResourceManager.GetString("CshtmlView_WrongViewBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has a DisplayColumn attribute for {1}, but property {1} does not exist..
        /// </summary>
        public static string DataAnnotationsModelMetadataProvider_UnknownProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has a DisplayColumn attribute for {1}, but property {1} does not have a public getter..
        /// </summary>
        public static string DataAnnotationsModelMetadataProvider_UnreadableProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnreadableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type {0} must have a public constructor which accepts three parameters of types {1}, {2}, and {3}.
        /// </summary>
        public static string DataAnnotationsModelValidatorProvider_ConstructorRequirements {
            get {
                return ResourceManager.GetString("DataAnnotationsModelValidatorProvider_ConstructorRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type {0} must have a public constructor which accepts two parameters of types {1} and {2}..
        /// </summary>
        public static string DataAnnotationsModelValidatorProvider_ValidatableConstructorRequirements {
            get {
                return ResourceManager.GetString("DataAnnotationsModelValidatorProvider_ValidatableConstructorRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.{2}{2}The request for &apos;{0}&apos; has found the following matching controllers:{1}.
        /// </summary>
        public static string DefaultControllerFactory_ControllerNameAmbiguous_WithoutRouteUrl {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ControllerNameAmbiguous_WithoutRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request (&apos;{1}&apos;) does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.{3}{3}The request for &apos;{0}&apos; has found the following matching controllers:{2}.
        /// </summary>
        public static string DefaultControllerFactory_ControllerNameAmbiguous_WithRouteUrl {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ControllerNameAmbiguous_WithRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple controller types were found that match the URL. This can happen if attribute routes on multiple controllers match the requested URL.{1}{1}The request has found the following matching controller types: {0}.
        /// </summary>
        public static string DefaultControllerFactory_DirectRouteAmbiguous {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_DirectRouteAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when trying to create a controller of type &apos;{0}&apos;. Make sure that the controller has a parameterless public constructor..
        /// </summary>
        public static string DefaultControllerFactory_ErrorCreatingController {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ErrorCreatingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The controller for path &apos;{0}&apos; was not found or does not implement IController..
        /// </summary>
        public static string DefaultControllerFactory_NoControllerFound {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_NoControllerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The controller type &apos;{0}&apos; must implement IController..
        /// </summary>
        public static string DefaultControllerFactory_TypeDoesNotSubclassControllerBase {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_TypeDoesNotSubclassControllerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The constructor to use for activating the constraint type &apos;{0}&apos; is ambiguous. Multiple constructors were found with the following number of parameters: {1}..
        /// </summary>
        public static string DefaultInlineConstraintResolver_AmbiguousCtors {
            get {
                return ResourceManager.GetString("DefaultInlineConstraintResolver_AmbiguousCtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find a constructor for constraint type &apos;{0}&apos; with the following number of parameters: {1}..
        /// </summary>
        public static string DefaultInlineConstraintResolver_CouldNotFindCtor {
            get {
                return ResourceManager.GetString("DefaultInlineConstraintResolver_CouldNotFindCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The constraint type &apos;{0}&apos; which is mapped to constraint key &apos;{1}&apos; must implement the IRouteConstraint interface..
        /// </summary>
        public static string DefaultInlineConstraintResolver_TypeNotConstraint {
            get {
                return ResourceManager.GetString("DefaultInlineConstraintResolver_TypeNotConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value &apos;{0}&apos; is not valid for {1}..
        /// </summary>
        public static string DefaultModelBinder_ValueInvalid {
            get {
                return ResourceManager.GetString("DefaultModelBinder_ValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A value is required..
        /// </summary>
        public static string DefaultModelBinder_ValueRequired {
            get {
                return ResourceManager.GetString("DefaultModelBinder_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of ticks for the TimeSpan value must be greater than or equal to 0..
        /// </summary>
        public static string DefaultViewLocationCache_NegativeTimeSpan {
            get {
                return ResourceManager.GetString("DefaultViewLocationCache_NegativeTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type {0} does not appear to implement Microsoft.Practices.ServiceLocation.IServiceLocator..
        /// </summary>
        public static string DependencyResolver_DoesNotImplementICommonServiceLocator {
            get {
                return ResourceManager.GetString("DependencyResolver_DoesNotImplementICommonServiceLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current request is ambiguous between the following action methods:{0}.
        /// </summary>
        public static string DirectRoute_AmbiguousMatch {
            get {
                return ResourceManager.GetString("DirectRoute_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A direct route for an action method cannot use the parameter &apos;action&apos;. Specify a literal path in place of this parameter to create a route to the action..
        /// </summary>
        public static string DirectRoute_InvalidParameter_Action {
            get {
                return ResourceManager.GetString("DirectRoute_InvalidParameter_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A direct route cannot use the parameter &apos;controller&apos;. Specify a literal path in place of this parameter to create a route to a controller..
        /// </summary>
        public static string DirectRoute_InvalidParameter_Controller {
            get {
                return ResourceManager.GetString("DirectRoute_InvalidParameter_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The route does not have any associated action descriptors. Routing requires that each direct route map to a non-empty set of actions..
        /// </summary>
        public static string DirectRoute_MissingActionDescriptors {
            get {
                return ResourceManager.GetString("DirectRoute_MissingActionDescriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The route does not have an associated controller descriptor. Routing requires that each direct route map to a single controller..
        /// </summary>
        public static string DirectRoute_MissingControllerDescriptor {
            get {
                return ResourceManager.GetString("DirectRoute_MissingControllerDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The route does not have an associated controller type. Routing requires that each direct route map to a single controller type..
        /// </summary>
        public static string DirectRoute_MissingControllerType {
            get {
                return ResourceManager.GetString("DirectRoute_MissingControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direct routing does not support per-route route handlers..
        /// </summary>
        public static string DirectRoute_RouteHandlerNotSupported {
            get {
                return ResourceManager.GetString("DirectRoute_RouteHandlerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ModelType property must not be null..
        /// </summary>
        public static string EnumHelper_InvalidMetadataParameter {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidMetadataParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string EnumHelper_InvalidParameterType {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid value parameter type &apos;{0}&apos;. Must match type parameter &apos;{1}&apos;..
        /// </summary>
        public static string EnumHelper_InvalidValueParameter {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidValueParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type &apos;{0}&apos; does not inherit from Exception..
        /// </summary>
        public static string ExceptionViewAttribute_NonExceptionType {
            get {
                return ResourceManager.GetString("ExceptionViewAttribute_NonExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The expression compiler was unable to evaluate the indexer expression &apos;{0}&apos; because it references the model parameter &apos;{1}&apos; which is unavailable..
        /// </summary>
        public static string ExpressionHelper_InvalidIndexerExpression {
            get {
                return ResourceManager.GetString("ExpressionHelper_InvalidIndexerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order must be greater than or equal to -1..
        /// </summary>
        public static string FilterAttribute_OrderOutOfRange {
            get {
                return ResourceManager.GetString("FilterAttribute_OrderOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The given filter instance must implement one or more of the following filter interfaces: {0}, {1}, {2}, {3}, {4}..
        /// </summary>
        public static string GlobalFilterCollection_UnsupportedFilterInstance {
            get {
                return ResourceManager.GetString("GlobalFilterCollection_UnsupportedFilterInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The GET and POST HTTP methods are not supported..
        /// </summary>
        public static string HtmlHelper_InvalidHttpMethod {
            get {
                return ResourceManager.GetString("HtmlHelper_InvalidHttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The specified HttpVerbs value is not supported. The supported values are Delete, Head, Put, Options, and Patch..
        /// </summary>
        public static string HtmlHelper_InvalidHttpVerb {
            get {
                return ResourceManager.GetString("HtmlHelper_InvalidHttpVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no ViewData item of type &apos;{1}&apos; that has the key &apos;{0}&apos;..
        /// </summary>
        public static string HtmlHelper_MissingSelectData {
            get {
                return ResourceManager.GetString("HtmlHelper_MissingSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter &apos;{0}&apos; must evaluate to an IEnumerable when multiple selection is allowed..
        /// </summary>
        public static string HtmlHelper_SelectExpressionNotEnumerable {
            get {
                return ResourceManager.GetString("HtmlHelper_SelectExpressionNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value must be greater than or equal to zero..
        /// </summary>
        public static string HtmlHelper_TextAreaParameterOutOfRange {
            get {
                return ResourceManager.GetString("HtmlHelper_TextAreaParameterOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The ViewData item that has the key &apos;{0}&apos; is of type &apos;{1}&apos; but must be of type &apos;{2}&apos;..
        /// </summary>
        public static string HtmlHelper_WrongSelectDataType {
            get {
                return ResourceManager.GetString("HtmlHelper_WrongSelectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The inline constraint resolver of type &apos;{0}&apos; was unable to resolve the following inline constraint: &apos;{1}&apos;..
        /// </summary>
        public static string HttpRouteBuilder_CouldNotResolveConstraint {
            get {
                return ResourceManager.GetString("HttpRouteBuilder_CouldNotResolveConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The key is invalid JQuery syntax because it is missing a closing bracket..
        /// </summary>
        public static string JQuerySyntaxMissingClosingBracket {
            get {
                return ResourceManager.GetString("JQuerySyntaxMissingClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This request has been blocked because sensitive information could be disclosed to third party web sites when this is used in a GET request. To allow GET requests, set JsonRequestBehavior to AllowGet..
        /// </summary>
        public static string JsonRequest_GetNotAllowed {
            get {
                return ResourceManager.GetString("JsonRequest_GetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The JSON request was too large to be deserialized..
        /// </summary>
        public static string JsonValueProviderFactory_RequestTooLarge {
            get {
                return ResourceManager.GetString("JsonValueProviderFactory_RequestTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when trying to create the IModelBinder &apos;{0}&apos;. Make sure that the binder has a public parameterless constructor..
        /// </summary>
        public static string ModelBinderAttribute_ErrorCreatingModelBinder {
            get {
                return ResourceManager.GetString("ModelBinderAttribute_ErrorCreatingModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type &apos;{0}&apos; does not implement the IModelBinder interface..
        /// </summary>
        public static string ModelBinderAttribute_TypeNotIModelBinder {
            get {
                return ResourceManager.GetString("ModelBinderAttribute_TypeNotIModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type &apos;{0}&apos; contains multiple attributes that inherit from CustomModelBinderAttribute..
        /// </summary>
        public static string ModelBinderDictionary_MultipleAttributes {
            get {
                return ResourceManager.GetString("ModelBinderDictionary_MultipleAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This property setter is obsolete, because its value is derived from ModelMetadata.Model now..
        /// </summary>
        public static string ModelMetadata_PropertyNotSettable {
            get {
                return ResourceManager.GetString("ModelMetadata_PropertyNotSettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This constructor is obsolete, because its functionality has been moved to MvcForm(ViewContext) now..
        /// </summary>
        public static string MvcForm_ConstructorObsolete {
            get {
                return ResourceManager.GetString("MvcForm_ConstructorObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;inherits&apos; keyword is not allowed when a &apos;{0}&apos; keyword is used..
        /// </summary>
        public static string MvcRazorCodeParser_CannotHaveModelAndInheritsKeyword {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_CannotHaveModelAndInheritsKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;{0}&apos; keyword must be followed by a type name on the same line..
        /// </summary>
        public static string MvcRazorCodeParser_ModelKeywordMustBeFollowedByTypeName {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_ModelKeywordMustBeFollowedByTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only one &apos;{0}&apos; statement is allowed in a file..
        /// </summary>
        public static string MvcRazorCodeParser_OnlyOneModelStatementIsAllowed {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_OnlyOneModelStatementIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The matched route does not include a &apos;controller&apos; route value, which is required..
        /// </summary>
        public static string MvcRouteHandler_RouteValuesHasNoController {
            get {
                return ResourceManager.GetString("MvcRouteHandler_RouteValuesHasNoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OutputCacheAttribute is not allowed on child actions which are children of an already cached child action..
        /// </summary>
        public static string OutputCacheAttribute_CannotNestChildCache {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_CannotNestChildCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OutputCacheAttribute for child actions only supports Duration, VaryByCustom, and VaryByParam values. Please do not set CacheProfile, Location, NoStore, SqlDependency, VaryByContentEncoding, or VaryByHeader values for child actions..
        /// </summary>
        public static string OutputCacheAttribute_ChildAction_UnsupportedSetting {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_ChildAction_UnsupportedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration must be a positive number..
        /// </summary>
        public static string OutputCacheAttribute_InvalidDuration {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VaryByParam must be &apos;*&apos;, &apos;none&apos;, or a semicolon-delimited list of keys..
        /// </summary>
        public static string OutputCacheAttribute_InvalidVaryByParam {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_InvalidVaryByParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Child actions are not allowed to perform redirect actions..
        /// </summary>
        public static string RedirectAction_CannotRedirectInChildAction {
            get {
                return ResourceManager.GetString("RedirectAction_CannotRedirectInChildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot create a descriptor for instance method &apos;{0}&apos; on type &apos;{1}&apos; because the type does not derive from ControllerBase..
        /// </summary>
        public static string ReflectedActionDescriptor_CannotCallInstanceMethodOnNonControllerType {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallInstanceMethodOnNonControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot call action method &apos;{0}&apos; on controller &apos;{1}&apos; because the parameter &apos;{2}&apos; is passed by reference..
        /// </summary>
        public static string ReflectedActionDescriptor_CannotCallMethodsWithOutOrRefParameters {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallMethodsWithOutOrRefParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot call action method &apos;{0}&apos; on controller &apos;{1}&apos; because the action method is a generic method..
        /// </summary>
        public static string ReflectedActionDescriptor_CannotCallOpenGenericMethods {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallOpenGenericMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot call action method &apos;{0}&apos; on controller &apos;{1}&apos; because the action method is a static method..
        /// </summary>
        public static string ReflectedActionDescriptor_CannotCallStaticMethod {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameters dictionary contains a null entry for parameter &apos;{0}&apos; of non-nullable type &apos;{1}&apos; for method &apos;{2}&apos; in &apos;{3}&apos;. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter..
        /// </summary>
        public static string ReflectedActionDescriptor_ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameters dictionary does not contain an entry for parameter &apos;{0}&apos; of type &apos;{1}&apos; for method &apos;{2}&apos; in &apos;{3}&apos;. The dictionary must contain an entry for each parameter, including parameters that have null values..
        /// </summary>
        public static string ReflectedActionDescriptor_ParameterNotInDictionary {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterNotInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameters dictionary contains an invalid entry for parameter &apos;{0}&apos; for method &apos;{1}&apos; in &apos;{2}&apos;. The dictionary contains a value of type &apos;{3}&apos;, but the parameter requires a value of type &apos;{4}&apos;..
        /// </summary>
        public static string ReflectedActionDescriptor_ParameterValueHasWrongType {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterValueHasWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter &apos;{0}&apos; on method &apos;{1}&apos; contains multiple attributes that inherit from CustomModelBinderAttribute..
        /// </summary>
        public static string ReflectedParameterBindingInfo_MultipleConverterAttributes {
            get {
                return ResourceManager.GetString("ReflectedParameterBindingInfo_MultipleConverterAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No url for remote validation could be found..
        /// </summary>
        public static string RemoteAttribute_NoUrlFound {
            get {
                return ResourceManager.GetString("RemoteAttribute_NoUrlFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; is invalid..
        /// </summary>
        public static string RemoteAttribute_RemoteValidationFailed {
            get {
                return ResourceManager.GetString("RemoteAttribute_RemoteValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The requested resource can only be accessed via SSL..
        /// </summary>
        public static string RequireHttpsAttribute_MustUseSsl {
            get {
                return ResourceManager.GetString("RequireHttpsAttribute_MustUseSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A path segment that contains more than one section, such as a literal section or a parameter, cannot contain a catch-all parameter..
        /// </summary>
        public static string Route_CannotHaveCatchAllInMultiSegment {
            get {
                return ResourceManager.GetString("Route_CannotHaveCatchAllInMultiSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A path segment cannot contain two consecutive parameters. They must be separated by a &apos;/&apos; or by a literal string..
        /// </summary>
        public static string Route_CannotHaveConsecutiveParameters {
            get {
                return ResourceManager.GetString("Route_CannotHaveConsecutiveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The route template separator character &apos;/&apos; cannot appear consecutively. It must be separated by either a parameter or a literal value..
        /// </summary>
        public static string Route_CannotHaveConsecutiveSeparators {
            get {
                return ResourceManager.GetString("Route_CannotHaveConsecutiveSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A catch-all parameter can only appear as the last segment of the route template..
        /// </summary>
        public static string Route_CatchAllMustBeLast {
            get {
                return ResourceManager.GetString("Route_CatchAllMustBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The constraint entry &apos;{0}&apos; on the route with route template &apos;{1}&apos; must have a string value or be of a type which implements &apos;{2}&apos;..
        /// </summary>
        public static string Route_InvalidConstraint {
            get {
                return ResourceManager.GetString("Route_InvalidConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The route parameter name &apos;{0}&apos; is invalid. Route parameter names must be non-empty and cannot contain these characters: &quot;{{&quot;, &quot;}}&quot;, &quot;/&quot;, &quot;?&quot;.
        /// </summary>
        public static string Route_InvalidParameterName {
            get {
                return ResourceManager.GetString("Route_InvalidParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The route template cannot start with a &apos;/&apos; or &apos;~&apos; character and it cannot contain a &apos;?&apos; character..
        /// </summary>
        public static string Route_InvalidRouteTemplate {
            get {
                return ResourceManager.GetString("Route_InvalidRouteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is an incomplete parameter in this path segment: &apos;{0}&apos;. Check that each &apos;{{&apos; character has a matching &apos;}}&apos; character..
        /// </summary>
        public static string Route_MismatchedParameter {
            get {
                return ResourceManager.GetString("Route_MismatchedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The route parameter name &apos;{0}&apos; appears more than one time in the route template..
        /// </summary>
        public static string Route_RepeatedParameter {
            get {
                return ResourceManager.GetString("Route_RepeatedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The prefix &apos;{0}&apos; of the route area named &apos;{1}&apos; on the controller named &apos;{2}&apos; cannot end with a forward slash..
        /// </summary>
        public static string RouteAreaPrefix_CannotEnd_WithForwardSlash {
            get {
                return ResourceManager.GetString("RouteAreaPrefix_CannotEnd_WithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The route prefix &apos;{0}&apos; on the controller named &apos;{1}&apos; cannot begin or end with a forward slash..
        /// </summary>
        public static string RoutePrefix_CannotStartOrEnd_WithForwardSlash {
            get {
                return ResourceManager.GetString("RoutePrefix_CannotStartOrEnd_WithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only one route prefix attribute is supported. Remove extra attributes from the controller of type &apos;{0}&apos;..
        /// </summary>
        public static string RoutePrefix_CannotSupportMultiRoutePrefix {
            get {
                return ResourceManager.GetString("RoutePrefix_CannotSupportMultiRoutePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property &apos;prefix&apos; from route prefix attribute on controller of type &apos;{0}&apos; cannot be null..
        /// </summary>
        public static string RoutePrefix_PrefixCannotBeNull {
            get {
                return ResourceManager.GetString("RoutePrefix_PrefixCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The route template &apos;{0}&apos; on the action named &apos;{1}&apos; on the controller named &apos;{2}&apos; cannot begin with a forward slash..
        /// </summary>
        public static string RouteTemplate_CannotStart_WithForwardSlash {
            get {
                return ResourceManager.GetString("RouteTemplate_CannotStart_WithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to determine ModelMetadata for expression &apos;{0}&apos;..
        /// </summary>
        public static string SelectExtensions_InvalidExpressionParameterNoMetadata {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterNoMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to determine type of expression &apos;{0}&apos;..
        /// </summary>
        public static string SelectExtensions_InvalidExpressionParameterNoModelType {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterNoModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string SelectExtensions_InvalidExpressionParameterType {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return type &apos;{0}&apos; is not supported. Type must not have a &apos;{1}&apos; attribute..
        /// </summary>
        public static string SelectExtensions_InvalidExpressionParameterTypeHasFlags {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterTypeHasFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The SessionStateTempDataProvider class requires session state to be enabled..
        /// </summary>
        public static string SessionStateTempDataProvider_SessionStateDisabled {
            get {
                return ResourceManager.GetString("SessionStateTempDataProvider_SessionStateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An instance of {0} was found in the resolver as well as a custom registered provider in {1}. Please set only one or the other..
        /// </summary>
        public static string SingleServiceResolver_CannotRegisterTwoInstances {
            get {
                return ResourceManager.GetString("SingleServiceResolver_CannotRegisterTwoInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A route named &apos;{0}&apos; is already in the route collection. Route names must be unique.
        ///
        ///Duplicates:
        ///{1}
        ///{2}.
        /// </summary>
        public static string SubRouteCollection_DuplicateRouteName {
            get {
                return ResourceManager.GetString("SubRouteCollection_DuplicateRouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An operation that crossed a synchronization context failed. See the inner exception for more information..
        /// </summary>
        public static string SynchronizationContextUtil_ExceptionThrown {
            get {
                return ResourceManager.GetString("SynchronizationContextUtil_ExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The asynchronous action method &apos;{0}&apos; returns a Task, which cannot be executed synchronously..
        /// </summary>
        public static string TaskAsyncActionDescriptor_CannotExecuteSynchronously {
            get {
                return ResourceManager.GetString("TaskAsyncActionDescriptor_CannotExecuteSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to locate an appropriate template for type {0}..
        /// </summary>
        public static string TemplateHelpers_NoTemplate {
            get {
                return ResourceManager.GetString("TemplateHelpers_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Templates can be used only with field access, property access, single-dimension array index, or single-parameter custom indexer expressions..
        /// </summary>
        public static string TemplateHelpers_TemplateLimitations {
            get {
                return ResourceManager.GetString("TemplateHelpers_TemplateLimitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Collection template was used with an object of type &apos;{0}&apos;, which does not implement System.IEnumerable..
        /// </summary>
        public static string Templates_TypeMustImplementIEnumerable {
            get {
                return ResourceManager.GetString("Templates_TypeMustImplementIEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This file is automatically generated. Please do not modify the contents of this file..
        /// </summary>
        public static string TypeCache_DoNotModify {
            get {
                return ResourceManager.GetString("TypeCache_DoNotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Object type &apos;{1}&apos;..
        /// </summary>
        public static string TypeHelpers_CannotCreateInstance {
            get {
                return ResourceManager.GetString("TypeHelpers_CannotCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}.{1} must not return null..
        /// </summary>
        public static string TypeMethodMustNotReturnNull {
            get {
                return ResourceManager.GetString("TypeMethodMustNotReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The model object inside the metadata claimed to be compatible with {0}, but was actually {1}..
        /// </summary>
        public static string ValidatableObjectAdapter_IncompatibleType {
            get {
                return ResourceManager.GetString("ValidatableObjectAdapter_IncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter conversion from type &apos;{0}&apos; to type &apos;{1}&apos; failed. See the inner exception for more information..
        /// </summary>
        public static string ValueProviderResult_ConversionThrew {
            get {
                return ResourceManager.GetString("ValueProviderResult_ConversionThrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter conversion from type &apos;{0}&apos; to type &apos;{1}&apos; failed because no type converter can convert between these types..
        /// </summary>
        public static string ValueProviderResult_NoConverterExists {
            get {
                return ResourceManager.GetString("ValueProviderResult_NoConverterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The model item passed into the dictionary is null, but this dictionary requires a non-null model item of type &apos;{0}&apos;..
        /// </summary>
        public static string ViewDataDictionary_ModelCannotBeNull {
            get {
                return ResourceManager.GetString("ViewDataDictionary_ModelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The model item passed into the dictionary is of type &apos;{0}&apos;, but this dictionary requires a model item of type &apos;{1}&apos;..
        /// </summary>
        public static string ViewDataDictionary_WrongTModelType {
            get {
                return ResourceManager.GetString("ViewDataDictionary_WrongTModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A ViewMasterPage can be used only with content pages that derive from ViewPage or ViewPage&lt;TModel&gt;..
        /// </summary>
        public static string ViewMasterPage_RequiresViewPage {
            get {
                return ResourceManager.GetString("ViewMasterPage_RequiresViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execution of the child request failed. Please examine the InnerException for more information..
        /// </summary>
        public static string ViewPageHttpHandlerWrapper_ExceptionOccurred {
            get {
                return ResourceManager.GetString("ViewPageHttpHandlerWrapper_ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A ViewStartPage can be used only with with a page that derives from WebViewPage or another ViewStartPage..
        /// </summary>
        public static string ViewStartPage_RequiresMvcRazorView {
            get {
                return ResourceManager.GetString("ViewStartPage_RequiresMvcRazorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The ViewUserControl &apos;{0}&apos; cannot find an IViewDataContainer object. The ViewUserControl must be inside a ViewPage, a ViewMasterPage, or another ViewUserControl..
        /// </summary>
        public static string ViewUserControl_RequiresViewDataProvider {
            get {
                return ResourceManager.GetString("ViewUserControl_RequiresViewDataProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A ViewUserControl can be used only in pages that derive from ViewPage or ViewPage&lt;TModel&gt;..
        /// </summary>
        public static string ViewUserControl_RequiresViewPage {
            get {
                return ResourceManager.GetString("ViewUserControl_RequiresViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A master name cannot be specified when the view is a ViewUserControl..
        /// </summary>
        public static string WebFormViewEngine_UserControlCannotHaveMaster {
            get {
                return ResourceManager.GetString("WebFormViewEngine_UserControlCannotHaveMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The view at &apos;{0}&apos; must derive from ViewPage, ViewPage&lt;TModel&gt;, ViewUserControl, or ViewUserControl&lt;TModel&gt;..
        /// </summary>
        public static string WebFormViewEngine_WrongViewBase {
            get {
                return ResourceManager.GetString("WebFormViewEngine_WrongViewBase", resourceCulture);
            }
        }
    }
}
