export const TIPO_HABITACION = "TIPOHABITACION";
export const TIPO_IDENTIFICACION = "TIPOINDENTIFICACION";
export const REGISTRO_CIVIL_SUCCESS = "000";
export const TIPO_VEHICULO = "TIPOVEHICULO";
export const TIPO_AUSENTISMO = "TIPOAUSENTISMO";
export const ACCION_COLABORADOR = "ACCIONCOL";
export const CODIGO_AUSENTISMO = "AUS";
export const MOTIVO_BAJA = "MOTIVOBAJA";
export const CODIGO_BAJA = "BAJ";


export const GENERO = "GENERO";
export const ESTADOCIVIL = "ESTADOCIVIL";
export const SECTOR_TRANSPORTE = "SECTORTRANSPORTE";

export const TIPO_REQUISITO = "TIPOREQUISITO";
export const TIPO_ACCION = "ACCIONCOL";
export const TIPO_DEPARTAMENTO = "SECTOR";
export const TIPO_GRUPO_PERSONAL = "GRUPOPERSONAL";
export const TIPO_PROYECTO = "PROYECTO";
export const PASSCRYPTO = "@T!K@";

export const APIVENCIMIENTOAUSENTISMO = "http://localhost:8181/";

export const TIPOSERVICIOLAVANDERIA = "TIPOSERVICIOLAVANDERIA";

export const PORTAFOLIOCERTIFICACION = "PORTAFOLIO_CERTIFICACION";
export const UBICACIONCERTIFICACION = "UBICACION_CERTIFICACION";