
using com.cpp.calypso.comun.dominio;
using System;

namespace com.cpp.calypso.comun.aplicacion
{
    /// <summary>
    /// TODO: Se puede colocar una implementacion para cada tipo de Layout, 
    /// GetViewX, GeneratedXView
    /// </summary>
    public interface IAutoGeneratedView
    {
        View GetViewTree(Type type);

        View GetViewForm(Type type);

        View GetViewSearch(Type type);

        Tree GeneratedTreeView(Type type);

        Form GeneratedFormView(Type type);

        Search GeneratedSearchView(Type type);

        bool ConsiderFieldTree(Type type);
    }

}